#context const, current text should not be modified
[log]
    [log.node]
        addr = "127.0.0.1"
        port = 8010
    [log.context]
        log_level_array = ["trace", "debug", "info", "warn", "error"]
        format = "[%H:%M:%S %z] [%n] [%s] [%^%L%$] [%!] [thread %t] %v"
        level = 2   # "debug"
        log_file = "server.log"
        log_file_path= "./"
        log_roll_size = 10000000
        log_roll_count = 10
        logger_name="logname"
[login]
    port = 88
    tokenlife = 3600
[guid]
    [guid.node]
        addr = "127.0.0.1"
        port = 8081
[http]
    addr="127.0.0.1"
    port=80
    rootJsonPath="http"
    rootHtmlPath = "http"
    resRootPath="dist"
    wsPath = "ws"

[jwt]
    issuer="alqaz"
    type="JWS"
    key="key"
    noAuthUrl=["/http/User/Regist", "/http/User/Login", "/http/PayOrders/getOrderPage", "/http/PayOrders/getOrderPage2"]
    superuser="alqaz"
    superpass="123456"
    timeout=3600

[timezone]
    defaultTimeZone="Asia/Shanghai"

[transport]
    addr="127.0.0.1"
    port=10087
    timeout=3600

[nanomsg]
    [nanomsg.rep]
        addr="127.0.0.1"
        port=9001

[dbmgr]
    databasetype=1  #0 postgresql; 1 sqlite3
    databasemodel=0 #embed; 1 alone
    databasedebug=false #true or false
    [dbmgr.sqlite]
        sqlitepath="./"
        sqlitename = "db.db"
    [dbmgr.postgresql]
        dbname="demo"
        addr="127.0.0.1"
        port=5432
        user="postgres"
        pass="123456"
        useSSL=0
    [dbmgr.redis]
        addr="127.0.0.1"
        port=6379
        user=""
        pass=""
        useSSL=0
    [dbmgr.tcpserver]
        addr="127.0.0.1"
        port=5400
        useSSL=0
    [dbmgr.nngserver]
        addr="*"
        port=5401
        useSSL=0
    [dbmgr.tcpclient]
        addr= "127.0.0.1"# "106.52.167.54"
        port=5400
        useSSL=0
    [dbmgr.nngclient]
        addr= "127.0.0.1" #"106.52.167.54"
        port=5401
        useSSL=0
